apiVersion: v1
kind: Secret
metadata:
  name: docker-login
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMjAuNzcuOTcuMjA2OjgwNzciOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WW14cmFtRnNhV3hwIgoJCX0KCX0KfQo=