// Code generated by goctl. DO NOT EDIT!
// Source: identity.proto

package identity

import (
	"context"
	identitypb2 "fgzs/internal/app/identity/rpc/identitypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClearTokenReq     = identitypb2.ClearTokenReq
	ClearTokenResp    = identitypb2.ClearTokenResp
	GenerateTokenReq  = identitypb2.GenerateTokenReq
	GenerateTokenResp = identitypb2.GenerateTokenResp
	Token             = identitypb2.Token
	ValidateTokenReq  = identitypb2.ValidateTokenReq
	ValidateTokenResp = identitypb2.ValidateTokenResp

	Identity interface {
		//  生成token
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		//  验证token
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		//  清除token
		ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

// 生成token
func (m *defaultIdentity) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := identitypb2.NewIdentityClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

// 验证token
func (m *defaultIdentity) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := identitypb2.NewIdentityClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

// 清除token
func (m *defaultIdentity) ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error) {
	client := identitypb2.NewIdentityClient(m.cli.Conn())
	return client.ClearToken(ctx, in, opts...)
}
